# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kirby Hermansen 
author: Kirby Hermansen

header_pages:
  - index.html
  - research.html

faviconTags: | #
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon/favicon-16x16.png">
  <link rel="manifest" href="/assets/images/favicon/site.webmanifest">
  <link rel="mask-icon" href="/assets/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">


email: hermanse@nscl.msu.edu
description: "Nuclear Physicist Kirby Hermansen"
url: "https://kirbyherm.github.io" # the base hostname & protocol for your site
twitter_username: kirbyherm 
github_username:  kirbyherm 
linkedin_username: kirbyhermansen

# Build settings
markdown: kramdown
theme: minima

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "page"

sass:
    sass_dir: _sass

